#
# Debian image to build the Ceylon SDK
# It needs the output generated by a ceylon/ceylon-build image to do its work
#
FROM ceylon/base-package-deb

MAINTAINER Tako Schotanus <tako@ceylon-lang.org>

LABEL org.ceylon-lang.dockerfile.description="Debian image to build the Ceylon SDK" \
    org.ceylon-lang.dockerfile.vendor="RedHat" \
    org.ceylon-lang.dockerfile.version="1.0"

ADD build.sh /home/ceylon/build.sh

ENTRYPOINT ["/home/ceylon/build.sh"]
CMD []

